config/routes.rb
MeetupCalendarSync::Application.routes.draw do

  scope :module => 'google_gateway' do
    get 'google/request_auth',
        :to => 'authorizations#create',
        :as => 'request_google_auth'
    get 'google/auth_callback',
        :to => 'authorizations#callback',
        :as => 'google_auth_callback'

    get   'google/calendars',
          :to => 'calendars#index',
          :as => 'google_calendars'
    get   'google/calendars/edit',
          :to => 'calendars#edit',
          :as => 'edit_google_calendars'
    post  'google/calendars',
          :to => 'calendars#update',
          :as => 'update_google_calendars'
  end

  root 'root#index'

end

app/models/local_time.rb
class LocalTime

  def self.convert(milliseconds)
    Time.at(milliseconds / 1000).in_time_zone(Rails.application.config.time_zone)
  end

end

app/models/meetup_event.rb
class MeetupEvent < ActiveRecord::Base
  self.primary_key = "meetup_event_id"

  belongs_to  :meetup_group,      foreign_key: "meetup_group_id"
  has_many    :published_events,  foreign_key: "source_id"

  class << self
    def requires_sync
      where(requires_sync: true)
    end

    def from_api_response(response)
      start_time  = LocalTime.convert(response['time'].to_i)
      end_time    = if response['duration'].blank?
                      start_time + 2.hours
                    else
                      LocalTime.convert(response['time'].to_i + response['duration'].to_i)
                    end
      result = self.new(
        meetup_event_id:    response['id'],
        meetup_group_id:    response['group']['id'],
        meetup_last_update: response['updated'].to_i,
        name:           response['name'],
        start_time:     start_time,
        end_time:       end_time,
        details:        response,
        requires_sync:  true
      )
      result
    end

  end

  def tags
    meetup_group.tags
  end

  def update_from(another_event)
    self.update_attributes(
      meetup_last_update: another_event.meetup_last_update,
      name:               another_event.name,
      start_time:         another_event.start_time,
      end_time:           another_event.end_time,
      details:            another_event.details,
      requires_sync:      true
    )
  end

  def published!
    update_attributes(requires_sync: false)
  end


  def group_name
    details.fetch('group', {}).fetch('name', '')
  end


  def url
    details.fetch('event_url', '')
  end


  def last_update
    LocalTime.convert(meetup_last_update)
  end


  def location_string
    location = details.fetch('venue', {})
    str  = "#{location['address_1']} #{location['address_2']}"
    str << ", #{location['city']}" if location['city'].present?
    str << ", #{location['state']}" if location['state'].present?
    str << " #{location['zip']}"
    str  = "#{location['name']}, #{str}" if location['name'].present?
    str.gsub(/\s+/, ' ').gsub(/\s\,/, ',')
  end


  def method_missing(msg, *args, &block)
    if self[:details].key?(msg.to_s)
      result = self[:details][msg.to_s]
    else
      super
    end
  end

end

app/models/meetup_group.rb
class MeetupGroup < ActiveRecord::Base
  self.primary_key = "meetup_group_id"

  has_many  :meetup_events, foreign_key: "meetup_group_id"

  class << self
    def enabled
      where(enable_sync: true)
    end
  end

end

app/models/output_calendar.rb
class OutputCalendar < ImmutableStruct.new(:name, :id, :service, :tags, :access_params)

  def self.default
    calendar_setting = Setting.where(key: 'output_calendars').first
    return nil if calendar_setting.blank?
    default_calendar = calendar_setting.value.find do |cal|
      tags = cal.fetch('tags', [])
      tags.include?('default') || tags.include?('primary')
    end
    return nil if default_calendar.blank?
    new(default_calendar.symbolize_keys)
  end

end

app/models/published_event.rb
class PublishedEvent < ActiveRecord::Base
  self.primary_key = "source_id"
  belongs_to  :meetup_group, foreign_key: "meetup_group_id"
  serialize :details, HashSerializer
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  self.primary_key = "key"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    @page = RootPage.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # There is no real front-end for this application beyond of OAuth.
  # There is no need for view helper code.
  # It's a pretty heinous way to do the job anyway.

  def page; @page; end
end

app/views/google_calendar/list_page.html.erb
<%= link_to 'Edit Selected Calendars' %>

<h2>Selected Google Calendars</h2>
<% @page.selected_calendars.each do |cal| %>
  <div>
    <strong><%= cal['name'] %></strong>
    <% if cal['tags'].present? %>
      <em>(<% cal['tags'].join(', ') %>)</em>
    <% else %>
      (no tags)
    <% end %>
  </div>
<% end -%>

<h2>All Google Calendars</h2>
<% @page.discovered_calendars.each do |cal| %>
  <div>
    <strong><%= cal.summary %></strong>:
    <%= cal.description %>
  </div>
<% end -%>

app/views/google_calendar/requires_auth.html.erb
<!-- List calendars if authorized. -->
Re-auth please!

app/views/google_gateway/authorizations/oauth_error.html.erb
OAuthError

Retry?

app/views/google_gateway/calendars/authorization_required.html.erb
<!-- List calendars if authorized. -->
Re-auth please!

app/views/google_gateway/calendars/edit.html.erb
<h1>Select Google Calendars as Sync Targets</h1>

<%= form_for 'google_calendars', url: update_google_calendars_path do |f| %>

  <% @page.discovered_calendars.each.with_index do |gcal, idx| %>
    <div class="discovered-calendar">
      <p><strong><%= gcal.summary %></strong> (<%= gcal.id %>)</p>
      <p><%= gcal.description %></p>
      <%= hidden_field_tag "google_calendars[#{idx}][name]", gcal.summary %>
      <%= hidden_field_tag "google_calendars[#{idx}][id]", gcal.id %>
      <%= hidden_field_tag "google_calendars[#{idx}][selected]", false %>
      <%= check_box_tag "google_calendars[#{idx}][selected]", true, page.selected?(gcal) %>
      <%= text_field_tag "google_calendars[#{idx}][tags]", page.tag_text_for(gcal) %>
    </div>
  <% end -%>

  <p class="button"><%= f.submit 'Set Selected Calendars' %></p>
<% end %>

app/views/google_gateway/calendars/index.html.erb
<!-- List calendars if authorized. -->

app/views/google_gateway/calendars/list_page.html.erb
<%= link_to 'Edit Selected Calendars', edit_google_calendars_path %>

<h2>Selected Google Calendars</h2>
<% @page.selected_calendars.each do |cal| %>
  <div>
    <strong><%= cal['name'] %></strong>
    <% if cal['tags'].present? %>
      <em>(<%= cal['tags'].join(', ') %>)</em>
    <% else %>
      (no tags)
    <% end %>
  </div>
<% end -%>

<h2>All Google Calendars</h2>
<% @page.discovered_calendars.each do |cal| %>
  <div>
    <strong><%= cal.summary %></strong>:
    <%= cal.description %>
  </div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HoustonTechCalendar</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.erb
<h1>Meetup Calendar Sync Documentation</h1>



<% if !page.credentials_exist? %>
  It looks like you haven't set up a Google Maps
  <%= link_to 'Request Auth', request_google_auth_path %>
<% end %>
<!--

To discuss:

Overview:
- High-level Concept and Primary Use Case
- Requires Some Setup
- Doesn't need to be a rails project but...

Meetup Setup:
- API Key Settings
- Adding Groups with a the rake task
- Fetching Events

Google Calendar Setup:
- API Key Creation
- Secrets File &amp; Credentials Setting
- Authenticating and Selecting Calendars
- Tags and details on tagging.


Code Modifications &amp; Contributions
- Models not the focus, and are simple or weird.
- Explain: interactors, requests, queries, registries, view models


Metrics:
- Events Synchronized
 -->